### PR TITLE
Merging latest changes to uwp from main voodootikigod repo

### PR DESCRIPTION
**Pull request by munyirik**
Contains:
1. Latest changes from upstream branch.
2. Minor updates to UWP code based on nan getting upgraded.
3. Change to enable serialport on IoT that hasn't changed - https://github.com/ms-iot/node-serialport/commit/e4d548b026a6a1d353ba67a1ec3cd46900a5a1ad

### CODE REVIEW

**Comment by munyirik** [comment]
@kunalspathak @ooeygui I need 2 sign-offs

**Comment by bfjelds** [comment]
+1

**Comment by kunalspathak** [comment]
+1

**Comment by munyirik** [comment]
@bfjelds please merge this since it has two +1's.

**Pull request merged**
